name: PackPlugin
on:
    push:
        branches:
            - master
        tags:
            - '*'

env:
    PLUGIN_NAME: TinectPlatformHtmlMinify
    PLUGIN_UPLOADER_VERSION: 0.3.2

jobs:
    CreateZip:
        runs-on: ubuntu-latest
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.3.2
        steps:
            -   name: Get the version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: BuildZip
                run: php frosh-plugin-upload.phar ext:zip ${PLUGIN_NAME}

            -   name: Upload Artefact
                uses: actions/upload-artifact@v2
                with:
                    name: ${{ env.PLUGIN_NAME }}
                    path: ${{ env.PLUGIN_NAME }}.zip

            -   name: Create Release in github
                if: startsWith(github.ref, 'refs/tags/')
                id: create_release
                uses: "marvinpinto/action-automatic-releases@latest"
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    prerelease: false
                    title: ${{ steps.get_version.outputs.VERSION }}
                    files: |
                        *.zip
