name: Test
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Shopware
              run: |
                  composer config minimum-stability RC
                  composer update --prefer-stable

            - name: Run PHPUnit
              run: |
                  wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
                  php phpunit --bootstrap vendor/autoload.php
